__all__ = ['cons_string_profile_matrix',
           'dna_count_nucleotides',
           'fib_recurrence_rabbits',
           'gc_content_computation',
           'hamm_distance',
           'iprb_mendels_first_law',
           'prot_transcription',
           'recv_dna_strand_complement',
           'rna_dna_transcription',
           'subs_motif_finder']